import { DEFAULT_ORG_ID, type OrgSnapshot } from "./types";

export function createMessyStartupFixture(): OrgSnapshot {
  return {
    orgId: DEFAULT_ORG_ID,
    pushedAt: new Date().toISOString(),
    source: "fixture",
    notes:
      "A Grok Bot company that started lean, then hired too many generalists and never closed v1 rooms.",
    nodes: [
      {
        id: "human-you",
        kind: "human",
        name: "You",
        title: "Founder",
        status: "active",
        lastActiveAt: "2026-09-19T15:00:00.000Z",
        notes: "Single human. Judgment only — not the dispatcher.",
      },
      {
        id: "bot-cos",
        kind: "bot",
        name: "Casey",
        title: "Chief of Staff",
        status: "active",
        lastActiveAt: "2026-09-19T14:40:00.000Z",
        notes: "Single entry point. Routes outcomes. Should push this map.",
      },
      {
        id: "bot-gtm",
        kind: "bot",
        name: "Jules",
        title: "GTM lead",
        status: "active",
        lastActiveAt: "2026-09-19T11:10:00.000Z",
        notes: "Owns outbound + account health. One outcome.",
      },
      {
        id: "bot-prospector",
        kind: "bot",
        name: "Nia",
        title: "Prospector",
        status: "active",
        lastActiveAt: "2026-09-18T22:05:00.000Z",
        notes: "Stable specialist under Jules. Should stay.",
      },
      {
        id: "bot-recruiter",
        kind: "bot",
        name: "Chang",
        title: "Talent scout",
        status: "active",
        lastActiveAt: "2026-09-17T16:20:00.000Z",
        notes: "Sourcing only. Never emails a candidate without approval.",
      },
      {
        id: "bot-em",
        kind: "bot",
        name: "Emily",
        title: "Eng manager",
        status: "active",
        lastActiveAt: "2026-09-19T09:00:00.000Z",
        notes: "Breaks work down. Does not write production code.",
      },
      {
        id: "bot-eng-maya",
        kind: "bot",
        name: "Maya",
        title: "IC engineer",
        status: "active",
        lastActiveAt: "2026-09-19T08:12:00.000Z",
      },
      {
        id: "bot-eng-rio",
        kind: "bot",
        name: "Rio",
        title: "IC engineer",
        status: "active",
        lastActiveAt: "2026-09-16T19:44:00.000Z",
      },
      {
        id: "bot-pm",
        kind: "bot",
        name: "Pete",
        title: "PM",
        status: "active",
        lastActiveAt: "2026-09-19T10:02:00.000Z",
        notes: "RFCs, research, launch notes. In too many rooms.",
      },
      {
        id: "bot-data",
        kind: "bot",
        name: "Ashley",
        title: "Data analyst",
        status: "active",
        lastActiveAt: "2026-09-19T07:30:00.000Z",
      },
      {
        id: "bot-expense",
        kind: "bot",
        name: "Tyler",
        title: "Expense manager",
        status: "active",
        lastActiveAt: "2026-09-18T18:00:00.000Z",
        notes: "Current owner of receipts. Hidden v0 still runs a nightly routine.",
      },
      {
        id: "bot-slides",
        kind: "bot",
        name: "Deck",
        title: "Slides",
        status: "active",
        lastActiveAt: "2026-09-15T13:11:00.000Z",
        notes: "Still sitting in the deprecated v1 launch room.",
      },
      {
        id: "bot-helper",
        kind: "bot",
        name: "Buddy",
        title: "General helper",
        status: "duplicate",
        lastActiveAt: "2026-09-12T12:00:00.000Z",
        notes: "The anti-pattern. Muddy memory. Merge or hide.",
      },
      {
        id: "bot-helper-copy",
        kind: "bot",
        name: "Buddy copy",
        title: "General helper",
        status: "duplicate",
        lastActiveAt: "2026-08-02T09:00:00.000Z",
        notes: "Duplicated for 'backup'. Copy did not get memory. Two generalists.",
      },
      {
        id: "bot-v1-coord",
        kind: "bot",
        name: "Launch v1",
        title: "v1 launch coordinator",
        status: "deprecated",
        lastActiveAt: "2026-03-14T17:00:00.000Z",
        notes: "Product shipped in April. Role never retired.",
      },
      {
        id: "bot-old-writer",
        kind: "bot",
        name: "Copy v1",
        title: "Website writer",
        status: "stale",
        lastActiveAt: "2026-04-02T11:22:00.000Z",
        notes: "Superseded by Pete + Deck. Still in Q2 planning.",
      },
      {
        id: "bot-hidden-expense",
        kind: "bot",
        name: "Receipts v0",
        title: "Expense manager",
        status: "hidden",
        lastActiveAt: "2026-09-18T06:00:00.000Z",
        notes: "Hidden from sidebar. Nightly routine still runs. Hide ≠ pause.",
      },
      {
        id: "bot-hidden-inbox",
        kind: "bot",
        name: "Inbox v0",
        title: "Inbox cleaner",
        status: "hidden",
        lastActiveAt: "2026-09-19T06:05:00.000Z",
        notes: "Hidden, still DMing Casey every morning. Shared computer leftovers.",
      },
      {
        id: "grp-website",
        kind: "group",
        name: "Website launch",
        title: "Shared outcome",
        status: "active",
        lastActiveAt: "2026-09-19T10:02:00.000Z",
        notes: "Right-sized: coordinator, builder, reviewer.",
      },
      {
        id: "grp-gtm",
        kind: "group",
        name: "GTM war room",
        title: "7 members — over the 6 cap",
        status: "active",
        lastActiveAt: "2026-09-19T11:10:00.000Z",
        notes: "Group chats are 2–6 Bots. This room is past the product limit.",
      },
      {
        id: "grp-v1",
        kind: "group",
        name: "v1 launch",
        title: "Deprecated room",
        status: "deprecated",
        lastActiveAt: "2026-04-01T20:00:00.000Z",
        notes: "Zombie project space. Close it. Do not delete Bots from here blindly.",
      },
      {
        id: "grp-q2",
        kind: "group",
        name: "Q2 planning",
        title: "Zombie space",
        status: "stale",
        lastActiveAt: "2026-06-30T16:00:00.000Z",
        notes: "No owner, no outcome. Two leftover members.",
      },
      {
        id: "grp-onboard",
        kind: "group",
        name: "Onboarding",
        title: "New-human context",
        status: "active",
        lastActiveAt: "2026-09-10T15:00:00.000Z",
        notes: "The room a new person should land in first.",
      },
    ],
    edges: [
      { id: "e-cos-you", from: "bot-cos", to: "human-you", kind: "reports_to" },
      { id: "e-gtm-cos", from: "bot-gtm", to: "bot-cos", kind: "reports_to" },
      { id: "e-pros-cos", from: "bot-prospector", to: "bot-cos", kind: "reports_to" },
      { id: "e-rec-cos", from: "bot-recruiter", to: "bot-cos", kind: "reports_to" },
      { id: "e-em-cos", from: "bot-em", to: "bot-cos", kind: "reports_to" },
      { id: "e-maya-cos", from: "bot-eng-maya", to: "bot-cos", kind: "reports_to" },
      { id: "e-rio-cos", from: "bot-eng-rio", to: "bot-cos", kind: "reports_to" },
      { id: "e-pm-cos", from: "bot-pm", to: "bot-cos", kind: "reports_to" },
      { id: "e-data-cos", from: "bot-data", to: "bot-cos", kind: "reports_to" },
      { id: "e-exp-cos", from: "bot-expense", to: "bot-cos", kind: "reports_to" },
      { id: "e-slides-cos", from: "bot-slides", to: "bot-cos", kind: "reports_to" },
      { id: "e-help-cos", from: "bot-helper", to: "bot-cos", kind: "reports_to" },
      { id: "e-helpc-cos", from: "bot-helper-copy", to: "bot-cos", kind: "reports_to" },
      { id: "e-v1-cos", from: "bot-v1-coord", to: "bot-cos", kind: "reports_to" },
      { id: "e-writer-cos", from: "bot-old-writer", to: "bot-cos", kind: "reports_to" },
      { id: "e-hexp-cos", from: "bot-hidden-expense", to: "bot-cos", kind: "reports_to" },
      { id: "e-hinb-cos", from: "bot-hidden-inbox", to: "bot-cos", kind: "reports_to" },

      { id: "e-m-pm-web", from: "bot-pm", to: "grp-website", kind: "member_of" },
      { id: "e-m-maya-web", from: "bot-eng-maya", to: "grp-website", kind: "member_of" },
      { id: "e-m-ash-web", from: "bot-data", to: "grp-website", kind: "member_of" },

      { id: "e-m-gtm-war", from: "bot-gtm", to: "grp-gtm", kind: "member_of" },
      { id: "e-m-nia-war", from: "bot-prospector", to: "grp-gtm", kind: "member_of" },
      { id: "e-m-deck-war", from: "bot-slides", to: "grp-gtm", kind: "member_of" },
      { id: "e-m-pete-war", from: "bot-pm", to: "grp-gtm", kind: "member_of" },
      { id: "e-m-bud-war", from: "bot-helper", to: "grp-gtm", kind: "member_of" },
      { id: "e-m-budc-war", from: "bot-helper-copy", to: "grp-gtm", kind: "member_of" },
      { id: "e-m-cos-war", from: "bot-cos", to: "grp-gtm", kind: "member_of" },

      { id: "e-m-v1c-v1", from: "bot-v1-coord", to: "grp-v1", kind: "member_of" },
      { id: "e-m-write-v1", from: "bot-old-writer", to: "grp-v1", kind: "member_of" },
      { id: "e-m-deck-v1", from: "bot-slides", to: "grp-v1", kind: "member_of" },

      { id: "e-m-pete-q2", from: "bot-pm", to: "grp-q2", kind: "member_of" },
      { id: "e-m-write-q2", from: "bot-old-writer", to: "grp-q2", kind: "member_of" },

      { id: "e-m-cos-on", from: "bot-cos", to: "grp-onboard", kind: "member_of" },
      { id: "e-m-rec-on", from: "bot-recruiter", to: "grp-onboard", kind: "member_of" },
      { id: "e-m-pete-on", from: "bot-pm", to: "grp-onboard", kind: "member_of" },

      { id: "e-h-nia-jules", from: "bot-prospector", to: "bot-gtm", kind: "handoff" },
      { id: "e-h-em-maya", from: "bot-em", to: "bot-eng-maya", kind: "handoff" },
      { id: "e-h-write-deck", from: "bot-old-writer", to: "bot-slides", kind: "handoff" },
      { id: "e-h-inbox-cos", from: "bot-hidden-inbox", to: "bot-cos", kind: "handoff" },

      { id: "e-s-gtm-pm", from: "bot-gtm", to: "bot-pm", kind: "shares_context" },
      { id: "e-s-exp-v0", from: "bot-expense", to: "bot-hidden-expense", kind: "shares_context" },
    ],
  };
}
