import { DEFAULT_ORG_ID, type OrgSnapshot } from "./types";

/** Logan May's Grok Bot sidebar + group rooms (this Mac). Names and memberships only. */
export function createMySetupFixture(): OrgSnapshot {
  return {
    orgId: DEFAULT_ORG_ID,
    pushedAt: new Date().toISOString(),
    source: "manual",
    notes:
      "Logan May Grok Bot layout from this device: sidebar sections, specialist bots, and outcome rooms. No transcripts.",
    nodes: [
      {
        id: "human-logan-may",
        kind: "human",
        name: "Logan May",
        title: "You",
        status: "active",
        lastActiveAt: new Date().toISOString(),
        notes: "Account owner. Judgment only — Log is the work door.",
      },
      {
        id: "bot-log",
        kind: "bot",
        name: "Log",
        title: "Chief of Staff",
        status: "active",
        lastActiveAt: "2026-09-19T16:00:58.991Z",
        notes: "Pinned. Default inbox for work asks. Routes to specialists and opens outcome rooms.",
      },
      {
        id: "bot-bot-creator",
        kind: "bot",
        name: "Bot Creator",
        title: "Creates Grok Bots",
        status: "active",
        lastActiveAt: "2026-09-19T16:00:56.093Z",
      },
      {
        id: "bot-bot-auditor",
        kind: "bot",
        name: "Bot Auditor",
        title: "Fleet auditor",
        status: "active",
        lastActiveAt: "2026-09-16T03:28:29.340Z",
      },
      {
        id: "bot-lab",
        kind: "bot",
        name: "Lab",
        title: "Self-improve lab",
        status: "active",
        lastActiveAt: "2026-09-10T13:57:02.512Z",
      },
      {
        id: "bot-bot-optimizer",
        kind: "bot",
        name: "Bot Optimizer",
        title: "Fleet auditor",
        status: "duplicate",
        lastActiveAt: "2026-09-14T18:36:38.684Z",
        notes: "Same job as Bot Auditor. Unassigned in the sidebar.",
      },
      {
        id: "bot-ship",
        kind: "bot",
        name: "Ship",
        title: "PR and shipping",
        status: "active",
        lastActiveAt: "2026-09-18T13:40:58.915Z",
        notes: "Owns the Factory coding lane.",
      },
      {
        id: "bot-writing",
        kind: "bot",
        name: "Writing",
        title: "HS writing / Incept",
        status: "active",
        lastActiveAt: "2026-09-15T15:20:34.795Z",
      },
      {
        id: "bot-x-growth",
        kind: "bot",
        name: "X Growth",
        title: "Account growth coach (@loganmay)",
        status: "active",
        lastActiveAt: "2026-09-18T16:27:39.925Z",
      },
      {
        id: "bot-ig-growth",
        kind: "bot",
        name: "IG Growth",
        title: "Instagram growth coach",
        status: "active",
        lastActiveAt: "2026-09-19T16:00:53.538Z",
        notes: "New. Not in a sidebar section yet.",
      },
      {
        id: "bot-vouchers",
        kind: "bot",
        name: "Vouchers",
        title: "Admissions vouchers / SIS",
        status: "stale",
        lastActiveAt: "2026-09-04T15:51:35.165Z",
      },
      {
        id: "bot-crm",
        kind: "bot",
        name: "CRM",
        title: "HubSpot / admissions board",
        status: "active",
        lastActiveAt: "2026-09-17T09:09:53.966Z",
      },
      {
        id: "bot-security",
        kind: "bot",
        name: "Security",
        title: "Supabase RLS",
        status: "stale",
        lastActiveAt: "2026-09-09T13:29:14.123Z",
      },
      {
        id: "bot-meetings",
        kind: "bot",
        name: "Meetings",
        title: "Meetings → actions",
        status: "stale",
        lastActiveAt: "2026-09-04T16:46:40.971Z",
      },
      {
        id: "bot-hiring",
        kind: "bot",
        name: "Hiring",
        title: "Hiring logistics",
        status: "stale",
        lastActiveAt: "2026-09-09T17:20:18.999Z",
      },
      {
        id: "bot-incidents",
        kind: "bot",
        name: "Incidents",
        title: "Production incidents",
        status: "stale",
        lastActiveAt: "2026-09-04T15:20:52.070Z",
      },
      {
        id: "bot-rhythm",
        kind: "bot",
        name: "Rhythm",
        title: "Ops / playbook",
        status: "stale",
        lastActiveAt: "2026-09-09T16:33:44.329Z",
        notes: "Pinned. Not in a sidebar section.",
      },
      {
        id: "bot-darwin-x",
        kind: "bot",
        name: "Darwin X",
        title: "Fleet evolution",
        status: "active",
        lastActiveAt: "2026-09-18T20:42:42.536Z",
      },
      {
        id: "bot-arena-harvest",
        kind: "bot",
        name: "Arena Harvest",
        title: "Darwin Arena scout",
        status: "active",
        lastActiveAt: "2026-09-19T15:47:44.571Z",
      },
      {
        id: "bot-arena-packet",
        kind: "bot",
        name: "Arena Packet",
        title: "Darwin Arena packet writer",
        status: "active",
        lastActiveAt: "2026-09-19T15:46:59.940Z",
      },
      {
        id: "bot-arena-judge",
        kind: "bot",
        name: "Arena Judge",
        title: "Darwin Arena judge",
        status: "active",
        lastActiveAt: "2026-09-19T15:46:55.842Z",
      },
      {
        id: "bot-arena-eval",
        kind: "bot",
        name: "Arena Eval",
        title: "Darwin Arena evaluator",
        status: "active",
        lastActiveAt: "2026-09-19T15:46:23.210Z",
      },
      {
        id: "sec-gt",
        kind: "group",
        name: "GT",
        title: "Sidebar section",
        status: "active",
      },
      {
        id: "sec-harness",
        kind: "group",
        name: "Harness",
        title: "Sidebar section",
        status: "active",
      },
      {
        id: "sec-factory",
        kind: "group",
        name: "Factory",
        title: "Sidebar section",
        status: "active",
      },
      {
        id: "sec-ops",
        kind: "group",
        name: "Ops",
        title: "Sidebar section",
        status: "active",
      },
      {
        id: "sec-writing-app",
        kind: "group",
        name: "Writing App",
        title: "Sidebar section",
        status: "active",
      },
      {
        id: "sec-personal",
        kind: "group",
        name: "Personal",
        title: "Sidebar section",
        status: "active",
      },
      {
        id: "grp-ig-growth",
        kind: "group",
        name: "ig-growth",
        title: "Group room",
        status: "active",
        lastActiveAt: "2026-09-19T16:00:50.108Z",
      },
      {
        id: "grp-darwin-arena",
        kind: "group",
        name: "darwin-arena",
        title: "Group room",
        status: "active",
        lastActiveAt: "2026-09-19T15:46:16.893Z",
      },
      {
        id: "grp-darwin-x",
        kind: "group",
        name: "darwin-x",
        title: "Group room",
        status: "active",
        lastActiveAt: "2026-09-15T18:26:55.483Z",
      },
      {
        id: "grp-self-improve",
        kind: "group",
        name: "self-improve",
        title: "Group room",
        status: "active",
        lastActiveAt: "2026-09-08T20:15:25.751Z",
      },
      {
        id: "grp-crm-segment-builder",
        kind: "group",
        name: "crm-segment-builder",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-09T15:46:06.815Z",
      },
      {
        id: "grp-supabase-rls",
        kind: "group",
        name: "supabase-rls",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-09T13:29:12.586Z",
      },
      {
        id: "grp-writing-course",
        kind: "group",
        name: "writing-course",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-04T16:09:59.528Z",
      },
      {
        id: "grp-vouchers-sis",
        kind: "group",
        name: "vouchers-sis",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-04T15:41:06.350Z",
      },
      {
        id: "grp-x-growth",
        kind: "group",
        name: "x-growth",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-04T15:37:15.493Z",
      },
      {
        id: "grp-meetings-actions",
        kind: "group",
        name: "meetings-actions",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-04T15:28:39.138Z",
      },
      {
        id: "grp-incidents",
        kind: "group",
        name: "incidents",
        title: "Group room",
        status: "stale",
        lastActiveAt: "2026-09-04T15:21:22.066Z",
      },
    ],
    edges: [
      { id: "e-log-logan", from: "bot-log", to: "human-logan-may", kind: "reports_to" },
      { id: "e-bot-creator-log", from: "bot-bot-creator", to: "bot-log", kind: "reports_to" },
      { id: "e-bot-auditor-log", from: "bot-bot-auditor", to: "bot-log", kind: "reports_to" },
      { id: "e-lab-log", from: "bot-lab", to: "bot-log", kind: "reports_to" },
      { id: "e-bot-optimizer-log", from: "bot-bot-optimizer", to: "bot-log", kind: "reports_to" },
      { id: "e-ship-log", from: "bot-ship", to: "bot-log", kind: "reports_to" },
      { id: "e-writing-log", from: "bot-writing", to: "bot-log", kind: "reports_to" },
      { id: "e-x-growth-log", from: "bot-x-growth", to: "bot-log", kind: "reports_to" },
      { id: "e-ig-growth-log", from: "bot-ig-growth", to: "bot-log", kind: "reports_to" },
      { id: "e-vouchers-log", from: "bot-vouchers", to: "bot-log", kind: "reports_to" },
      { id: "e-crm-log", from: "bot-crm", to: "bot-log", kind: "reports_to" },
      { id: "e-security-log", from: "bot-security", to: "bot-log", kind: "reports_to" },
      { id: "e-meetings-log", from: "bot-meetings", to: "bot-log", kind: "reports_to" },
      { id: "e-hiring-log", from: "bot-hiring", to: "bot-log", kind: "reports_to" },
      { id: "e-incidents-log", from: "bot-incidents", to: "bot-log", kind: "reports_to" },
      { id: "e-rhythm-log", from: "bot-rhythm", to: "bot-log", kind: "reports_to" },
      { id: "e-darwin-x-log", from: "bot-darwin-x", to: "bot-log", kind: "reports_to" },
      { id: "e-arena-harvest-log", from: "bot-arena-harvest", to: "bot-log", kind: "reports_to" },
      { id: "e-arena-packet-log", from: "bot-arena-packet", to: "bot-log", kind: "reports_to" },
      { id: "e-arena-judge-log", from: "bot-arena-judge", to: "bot-log", kind: "reports_to" },
      { id: "e-arena-eval-log", from: "bot-arena-eval", to: "bot-log", kind: "reports_to" },
      { id: "e-log-gt", from: "bot-log", to: "sec-gt", kind: "member_of" },
      { id: "e-vouchers-gt", from: "bot-vouchers", to: "sec-gt", kind: "member_of" },
      { id: "e-crm-gt", from: "bot-crm", to: "sec-gt", kind: "member_of" },
      { id: "e-bot-creator-harness", from: "bot-bot-creator", to: "sec-harness", kind: "member_of" },
      { id: "e-bot-auditor-harness", from: "bot-bot-auditor", to: "sec-harness", kind: "member_of" },
      { id: "e-lab-harness", from: "bot-lab", to: "sec-harness", kind: "member_of" },
      { id: "e-ship-factory", from: "bot-ship", to: "sec-factory", kind: "member_of" },
      { id: "e-security-ops", from: "bot-security", to: "sec-ops", kind: "member_of" },
      { id: "e-meetings-ops", from: "bot-meetings", to: "sec-ops", kind: "member_of" },
      { id: "e-hiring-ops", from: "bot-hiring", to: "sec-ops", kind: "member_of" },
      { id: "e-incidents-ops", from: "bot-incidents", to: "sec-ops", kind: "member_of" },
      { id: "e-writing-writing-app", from: "bot-writing", to: "sec-writing-app", kind: "member_of" },
      { id: "e-x-growth-personal", from: "bot-x-growth", to: "sec-personal", kind: "member_of" },
      { id: "e-ig-m-ig", from: "bot-ig-growth", to: "grp-ig-growth", kind: "member_of" },
      { id: "e-log-m-ig", from: "bot-log", to: "grp-ig-growth", kind: "member_of" },
      { id: "e-log-m-arena", from: "bot-log", to: "grp-darwin-arena", kind: "member_of" },
      { id: "e-harvest-m-arena", from: "bot-arena-harvest", to: "grp-darwin-arena", kind: "member_of" },
      { id: "e-eval-m-arena", from: "bot-arena-eval", to: "grp-darwin-arena", kind: "member_of" },
      { id: "e-packet-m-arena", from: "bot-arena-packet", to: "grp-darwin-arena", kind: "member_of" },
      { id: "e-judge-m-arena", from: "bot-arena-judge", to: "grp-darwin-arena", kind: "member_of" },
      { id: "e-log-m-darwin-x", from: "bot-log", to: "grp-darwin-x", kind: "member_of" },
      { id: "e-darwin-x-m-darwin-x", from: "bot-darwin-x", to: "grp-darwin-x", kind: "member_of" },
      { id: "e-lab-m-darwin-x", from: "bot-lab", to: "grp-darwin-x", kind: "member_of" },
      { id: "e-log-m-self", from: "bot-log", to: "grp-self-improve", kind: "member_of" },
      { id: "e-lab-m-self", from: "bot-lab", to: "grp-self-improve", kind: "member_of" },
      { id: "e-auditor-m-self", from: "bot-bot-auditor", to: "grp-self-improve", kind: "member_of" },
      { id: "e-creator-m-self", from: "bot-bot-creator", to: "grp-self-improve", kind: "member_of" },
      { id: "e-rhythm-m-self", from: "bot-rhythm", to: "grp-self-improve", kind: "member_of" },
      { id: "e-log-m-crm", from: "bot-log", to: "grp-crm-segment-builder", kind: "member_of" },
      { id: "e-crm-m-crm", from: "bot-crm", to: "grp-crm-segment-builder", kind: "member_of" },
      { id: "e-ship-m-crm", from: "bot-ship", to: "grp-crm-segment-builder", kind: "member_of" },
      { id: "e-log-m-rls", from: "bot-log", to: "grp-supabase-rls", kind: "member_of" },
      { id: "e-security-m-rls", from: "bot-security", to: "grp-supabase-rls", kind: "member_of" },
      { id: "e-log-m-writing", from: "bot-log", to: "grp-writing-course", kind: "member_of" },
      { id: "e-writing-m-writing", from: "bot-writing", to: "grp-writing-course", kind: "member_of" },
      { id: "e-ship-m-writing", from: "bot-ship", to: "grp-writing-course", kind: "member_of" },
      { id: "e-log-m-vouchers", from: "bot-log", to: "grp-vouchers-sis", kind: "member_of" },
      { id: "e-vouchers-m-vouchers", from: "bot-vouchers", to: "grp-vouchers-sis", kind: "member_of" },
      { id: "e-ship-m-vouchers", from: "bot-ship", to: "grp-vouchers-sis", kind: "member_of" },
      { id: "e-log-m-x", from: "bot-log", to: "grp-x-growth", kind: "member_of" },
      { id: "e-x-m-x", from: "bot-x-growth", to: "grp-x-growth", kind: "member_of" },
      { id: "e-log-m-meetings", from: "bot-log", to: "grp-meetings-actions", kind: "member_of" },
      { id: "e-meetings-m-meetings", from: "bot-meetings", to: "grp-meetings-actions", kind: "member_of" },
      { id: "e-log-m-incidents", from: "bot-log", to: "grp-incidents", kind: "member_of" },
      { id: "e-incidents-m-incidents", from: "bot-incidents", to: "grp-incidents", kind: "member_of" },

      { id: "e-h-ship-log", from: "bot-ship", to: "bot-log", kind: "handoff" },
      { id: "e-h-harvest-eval", from: "bot-arena-harvest", to: "bot-arena-eval", kind: "handoff" },
      { id: "e-h-incidents-security", from: "bot-incidents", to: "bot-security", kind: "handoff" },
      { id: "e-s-auditor-optimizer", from: "bot-bot-auditor", to: "bot-bot-optimizer", kind: "shares_context" },
    ],
  };
}
